## Descriptive analysis _ tips 

In [1]:
import pandas as pd 
import numpy as np 

In [3]:
np.random.randint(1, 20, size=(10, 3))

array([[12,  3, 11],
       [ 8,  7,  5],
       [19,  5,  6],
       [ 3,  3, 14],
       [19,  8, 11],
       [12,  2, 13],
       [ 2,  2,  9],
       [ 6,  5, 18],
       [12,  7, 10],
       [ 2, 17,  7]])

In [32]:
np.random.seed(10)
[np.random.randint(1,20,9) for i in range(10)]

[array([10,  5, 16,  1, 18, 17, 18,  9, 10]),
 array([ 1, 11,  9,  5, 17,  5, 16, 12, 12]),
 array([ 2,  9,  5, 15, 18, 14,  6, 14, 14]),
 array([13,  2,  5, 19, 14, 12, 11, 10, 16]),
 array([19, 17,  8, 12, 18, 15,  8, 12,  2]),
 array([ 1, 13,  6,  5,  8, 19, 13,  3,  9]),
 array([16, 14, 16,  7, 11, 12, 17, 13,  1]),
 array([18, 16, 13,  9, 11, 14, 12,  2, 19]),
 array([14,  9, 10,  6,  1, 19,  4, 17, 19]),
 array([17, 15, 16, 18, 19, 15, 17, 11, 18])]

In [45]:
np.random.seed(10)
sample = pd.DataFrame([np.random.randint(1,20,9) for i in range(10)], columns =['a','b','c','d','e','f','g','h','i'])
sample['goup'] =['f','f','a','a','a','b','c','d','c','d']

In [46]:
sample

a   b   c   d   e   f   g   h   i goup
0  10   5  16   1  18  17  18   9  10    f
1   1  11   9   5  17   5  16  12  12    f
2   2   9   5  15  18  14   6  14  14    a
3  13   2   5  19  14  12  11  10  16    a
4  19  17   8  12  18  15   8  12   2    a
5   1  13   6   5   8  19  13   3   9    b
6  16  14  16   7  11  12  17  13   1    c
7  18  16  13   9  11  14  12   2  19    d
8  14   9  10   6   1  19   4  17  19    c
9  17  15  16  18  19  15  17  11  18    d

#### 통계치 세분화 _ describe 

In [39]:
display(sample['a'].describe(percentiles= [0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]))

count    10.000000
mean     11.100000
std       7.218033
min       1.000000
5%        1.000000
10%       1.000000
20%       1.800000
30%       7.600000
40%      11.800000
50%      13.500000
60%      14.800000
70%      16.300000
80%      17.200000
90%      18.100000
max      19.000000
Name: a, dtype: float64

In [40]:
display(sample[sample['a']>5]['b'].describe(percentiles= [0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]))

count     7.000000
mean     11.142857
std       5.871643
min       2.000000
5%        2.900000
10%       3.800000
20%       5.800000
30%       8.200000
40%      11.000000
50%      14.000000
60%      14.600000
70%      15.200000
80%      15.800000
90%      16.400000
max      17.000000
Name: b, dtype: float64

#### quantile --> 분위수 찾기 

In [42]:
sample['a'].quantile(0.9)

18.1

#### 누적합 구하기 

In [47]:
sample['consum_a'] = sample['a'].cumsum()
sample

a   b   c   d   e   f   g   h   i goup  consum_a
0  10   5  16   1  18  17  18   9  10    f        10
1   1  11   9   5  17   5  16  12  12    f        11
2   2   9   5  15  18  14   6  14  14    a        13
3  13   2   5  19  14  12  11  10  16    a        26
4  19  17   8  12  18  15   8  12   2    a        45
5   1  13   6   5   8  19  13   3   9    b        46
6  16  14  16   7  11  12  17  13   1    c        62
7  18  16  13   9  11  14  12   2  19    d        80
8  14   9  10   6   1  19   4  17  19    c        94
9  17  15  16  18  19  15  17  11  18    d       111

####  groupby _ agg 펑션

In [51]:
sample.groupby('goup').agg({'a':'count', 'b':'sum'})

a   b
goup       
a     3  28
b     1  13
c     2  23
d     2  31
f     2  16

#### shift 함수  --> 해당 컬럼 몇번째 

In [52]:
sample['a_shift'] = sample['a'].shift(-2)    # 아래에서 2번째 
sample

a   b   c   d   e   f   g   h   i goup  consum_a  a_shift
0  10   5  16   1  18  17  18   9  10    f        10      2.0
1   1  11   9   5  17   5  16  12  12    f        11     13.0
2   2   9   5  15  18  14   6  14  14    a        13     19.0
3  13   2   5  19  14  12  11  10  16    a        26      1.0
4  19  17   8  12  18  15   8  12   2    a        45     16.0
5   1  13   6   5   8  19  13   3   9    b        46     18.0
6  16  14  16   7  11  12  17  13   1    c        62     14.0
7  18  16  13   9  11  14  12   2  19    d        80     17.0
8  14   9  10   6   1  19   4  17  19    c        94      NaN
9  17  15  16  18  19  15  17  11  18    d       111      NaN

#### group by후 몇번째 nth 

In [ ]:
raise_temp_l=data_rv2[(data_rv2['group1']!=0) & (data['Actual TPH']_rv2['skimm']==0)].groupby(['regen','group1'])[['date','rf1_air_temp','rf1_gas_flow_pv','gas_cumsum']].nth(5)

In [59]:
sample.groupby('goup')[['a','d','f']].nth(1)   # goup의 a,d,f에서 두번째 항목 cf> 0이 첫번째

a   d   f
goup            
a     13  19  12
c     14   6  19
d     17  18  15
f      1   5   5

#### q cut 범위별 range 자르기 

In [68]:
# q cut 범위별 range 자르기 
sample['range'] = pd.qcut(sample['a'],q=5)

# 소수점 없애기 precision 
sample['range_2'] = pd.qcut(sample['a'],q=5,precision=0)

# range를 범주화 시키기 
sample['range_labels'] = pd.qcut(sample['a'],q=5,labels=range(5))

# duplicates drop 추가
sample['range_labels_2'] = pd.qcut(sample['a'],q=5,duplicates='drop')

In [69]:
sample

a   b   c   d   e   f   g   h   i goup  consum_a  a_shift         range  \
0  10   5  16   1  18  17  18   9  10    f        10      2.0   (1.8, 11.8]   
1   1  11   9   5  17   5  16  12  12    f        11     13.0  (0.999, 1.8]   
2   2   9   5  15  18  14   6  14  14    a        13     19.0   (1.8, 11.8]   
3  13   2   5  19  14  12  11  10  16    a        26      1.0  (11.8, 14.8]   
4  19  17   8  12  18  15   8  12   2    a        45     16.0  (17.2, 19.0]   
5   1  13   6   5   8  19  13   3   9    b        46     18.0  (0.999, 1.8]   
6  16  14  16   7  11  12  17  13   1    c        62     14.0  (14.8, 17.2]   
7  18  16  13   9  11  14  12   2  19    d        80     17.0  (17.2, 19.0]   
8  14   9  10   6   1  19   4  17  19    c        94      NaN  (11.8, 14.8]   
9  17  15  16  18  19  15  17  11  18    d       111      NaN  (14.8, 17.2]   

        range_2 range_labels range_labels_2  
0   (2.0, 12.0]            1    (1.8, 11.8]  
1    (0.0, 2.0]            0   (0.999, 1.8]  
2   (2.0, 12.0]            1    (1.8, 11.8]  
3  (12.0, 15.0]            2   (11.8, 14.8]  
4  (17.0, 19.0]            4   (17.2, 19.0]  
5    (0.0, 2.0]            0   (0.999, 1.8]  
6  (15.0, 17.0]            3   (14.8, 17.2]  
7  (17.0, 19.0]            4   (17.2, 19.0]  
8  (12.0, 15.0]            2   (11.8, 14.8]  
9  (15.0, 17.0]            3   (14.8, 17.2]

* q cut 범위별 range 자르기 

ball_vari['rank'] = pd.qcut(ball_vari['vari'], q = 5 )  --> [1.*** ~ 3.****] 지저분하게 나옴.  

* 소수점 없애기 precision 

corr_data1['temp_mean_section'] = pd.qcut(corr_data1['inner_temp_pv/mean'],q=4,precision=0)

* range를 범주화 시키기 

target_comp_gss_20['rank2'] = pd.qcut(target_comp_gss_20['target_func'], q=5,labels=range(5))

* duplicates drop 추가 

gss_raw['raw_rank2'] = pd.qcut(gss_raw['RAS'],q=4,duplicates='drop')