## Numpy basic _ tips

In [1]:
import numpy as np
import pandas as pd

#### numpy 무작위 추출 _ choice 

In [2]:
list1=[1,2,3,4,5,6]
prob = [1/6,1/6,1/6,1/6,1/6,1/6] 
np.random.choice(list1,3,p=prob, replace=False)  ## 보통 replace를 건드리지 않지만, default는 True로 복원 추출, False의 경우는 비복원 추출로 한번 시행할때, 뽑힌것은 일단 배제하고 다음 것을 뽑는다.

array([4, 6, 1])

#### numpy 난수로 array 형성 

In [3]:
# 0에서 1사이의 값 중에서 난수 생성. 
# 0~1 사이의 숫자로 10 by 10 array 생성 
np.random.rand(10,10)    

array([[0.77587225, 0.44812035, 0.39917721, 0.79453465, 0.34860759,
        0.26338308, 0.28485649, 0.65606932, 0.97420786, 0.96283094],
       [0.34731088, 0.6601661 , 0.92787026, 0.75067489, 0.15099929,
        0.61130899, 0.90561933, 0.39993754, 0.67505665, 0.46957481],
       [0.83644003, 0.31973019, 0.22369573, 0.52870642, 0.91884783,
        0.5019949 , 0.93744785, 0.36877074, 0.44625383, 0.65119935],
       [0.94151417, 0.9104333 , 0.59613531, 0.19177539, 0.62209561,
        0.13780882, 0.11025708, 0.43591743, 0.56589989, 0.7247481 ],
       [0.72219387, 0.44661421, 0.86915961, 0.17095312, 0.39784174,
        0.4866574 , 0.37451356, 0.53282875, 0.43696766, 0.88682175],
       [0.70459896, 0.18585243, 0.49698403, 0.95257082, 0.45834902,
        0.47718805, 0.53110312, 0.70040955, 0.44573054, 0.66709041],
       [0.99504876, 0.96247424, 0.53155164, 0.72581894, 0.17928519,
        0.71021804, 0.75194192, 0.54535642, 0.86540122, 0.03120022],
       [0.63055341, 0.77683496, 0.9572675

#### numpy _ 정규분포

In [4]:
# 표준 정규분포에서 무작위 숫자 추출  // [0, 1) 범위에서 균일한 분포
np.random.randn(10,2)

array([[-0.01602827,  0.48901998],
       [-0.72668935,  0.19622593],
       [-0.33037874, -0.31251958],
       [ 0.59560543,  0.6461655 ],
       [ 1.27529283, -0.14711467],
       [ 0.51946248,  0.61025657],
       [ 0.72674609, -1.01479668],
       [-1.24022308, -0.28923723],
       [ 0.13733659,  0.5794789 ],
       [ 0.59879188,  0.84714172]])

In [5]:
# 표준정규분포 N(1, 0)이 아닌, 평균 μ, 표준편차 σ 를 갖는 정규분포 N(μ, σ2)의 난수를 생성
#σ * np.random.randn(…) + μ 와 같은 형태로 사용할 수 있습니다.
sigma, mu = 1.5, 2.0
c = sigma * np.random.randn(5) + mu
print(c)

[3.82552741 0.26375511 1.96103302 3.0397179  3.54920088]


#### numpy _ random randint, normal

In [6]:
# random.randint() 함수는 [최소값, 최대값)의 범위에서 임의의 정수
np.random.randint(2, size=5) # 는 [0, 2) 범위에서 다섯개의 임의의 정수를 생성.
np.random.randint(2, 4, size=5) # 는 [2, 4) 범위에서 다섯개의 임의의 정수를 생성합.
np.random.randint(1, 5, size=(2, 3)) # 는 [1, 5) 범위에서 (2, 3) 형태의 어레이를 생성합.

# random.normal() 함수는 정규 분포 (Normal distribution)로부터 샘플링된 난수를 반환
a = np.random.normal(0, 1, 2) # 어레이 a는 정규 분포 N(0,1)로부터 얻은 임의의 숫자 2개,
b = np.random.normal(1.5, 1.5, 4) # 어레이 b는 정규 분포 N(1.5,1.52)로부터 얻은 임의의 숫자 4개,
c = np.random.normal(3.0, 2.0, (2, 3)) # 어레이 c는 정규 분포 N(3.0,2.02)로부터 얻은 (2, 3) 형태의 임의의 숫자 어레이.           

In [7]:
print(a)
print(b)
print(c)

[-0.61492318  0.45664864]
[1.4492488  0.65954639 0.52751759 0.82031001]
[[4.2798224  0.06275657 3.80074831]
 [2.29153708 4.53768359 0.57793124]]


#### numpy random과 array 매서드로 dataframe

In [8]:
pd.DataFrame( np.random.randn(10,20), columns = ('col %d' % i for i in range(20)) )

sample = pd.DataFrame(np.random.randint(1,20,2) for i in range(10))

my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
display(pd.DataFrame(my_2darray))

0  1  2
0  1  2  3
1  4  5  6

#### np.where을 통한 조건부 정리

In [9]:
#np.where 
skimming_data2['group'] = np.where(skimming_data2['skimm'].between(4,6),'4~6',
                                  np.where(skimming_data2['skimm'].between(6,10),'7~10', '10~'))
# inull로 np where 
total_data['edge_crack'] = np.where(total_data['HFI 비고'].isnull(),0,1)

NameError: name 'skimming_data2' is not defined

https://codetorial.net/numpy/random.html