## Numpy basic _ tips

In [2]:
import numpy as np
import pandas as pd

#### numpy 무작위 추출 _ choice 

* 숫자가 존재하는 list에서 몇개씩(크기)무작위 추출

np.random.choice(리스트명,크기)

* 리스트1에서 무작위로 3개의 sample을 뽑을것인데, 각각이 뽑힐 확률을 prob를 따르겠다.

np.random.choice(리스트명,크기,p=??)  # p값에 확률을 지정할 수 있음 

In [3]:
list1=[1,2,3,4,5,6]
prob = [1/6,1/6,1/6,1/6,1/6,1/6] 
np.random.choice(list1,3,p=prob, replace=False)  ## 보통 replace를 건드리지 않지만, default는 True로 복원 추출, False의 경우는 비복원 추출로 한번 시행할때, 뽑힌것은 일단 배제하고 다음 것을 뽑는다.

array([2, 1, 4])

#### numpy 난수로 array 형성 

In [4]:
# 0에서 1사이의 값 중에서 난수 생성. 
# 0~1 사이의 숫자로 3 by 3 array 생성 
np.random.rand(3,3)    

array([[0.05883125, 0.10910574, 0.80219088],
       [0.62062839, 0.32927213, 0.49599276],
       [0.31572383, 0.69866739, 0.1934804 ]])

#### numpy _ 정규분포

In [5]:
# 표준 정규분포에서 무작위 숫자 추출  // [0, 1) 범위에서 균일한 분포
np.random.randn(3,2)   # 3 by 2 matrix

array([[ 0.3788141 ,  2.00119906],
       [ 0.77815122,  2.2918404 ],
       [-0.91964995,  1.88485368]])

In [6]:
# 표준정규분포 N(1, 0)이 아닌, 평균 μ, 표준편차 σ 를 갖는 정규분포 N(μ, σ2)의 난수를 생성
#σ * np.random.randn(…) + μ 와 같은 형태로 사용할 수 있습니다.
sigma, mu = 1.5, 2.0
c = sigma * np.random.randn(5) + mu
print(c)

[ 2.04683083  0.75465326  0.03066454  1.9809235  -0.48535755]


#### numpy _ random randint, normal

In [7]:
# random.randint() 함수는 [최소값, 최대값)의 범위에서 임의의 정수
np.random.randint(2, size=5) # 는 [0, 2) 범위에서 다섯개의 임의의 정수를 생성.
np.random.randint(2, 4, size=5) # 는 [2, 4) 범위에서 다섯개의 임의의 정수를 생성합.
np.random.randint(1, 5, size=(2, 3)) # 는 [1, 5) 범위에서 (2, 3) 형태의 어레이를 생성합.

# random.normal() 함수는 정규 분포 (Normal distribution)로부터 샘플링된 난수를 반환
a = np.random.normal(0, 1, 2) # 어레이 a는 정규 분포 N(0,1)로부터 얻은 임의의 숫자 2개,
b = np.random.normal(1.5, 1.5, 4) # 어레이 b는 정규 분포 N(1.5,1.52)로부터 얻은 임의의 숫자 4개,
c = np.random.normal(3.0, 2.0, (2, 3)) # 어레이 c는 정규 분포 N(3.0,2.02)로부터 얻은 (2, 3) 형태의 임의의 숫자 어레이.           

In [24]:
print(a)
print(b)
print(c)

[0.10083797 2.11860567]
[0.53259917 2.04129711 2.65236731 0.40806498]
[[0.38188509 6.1195246  5.08644936]
 [4.52018516 4.04262745 1.67071739]]


In [9]:
s = pd.Series(np.random.randint(0,7 , size =3))  # 0~7사이의 정수 생성, index는 10개
print(s)

0    5
1    1
2    2
dtype: int32


#### numpy random과 array 매서드로 dataframe

In [17]:
pd.DataFrame( np.random.randn(10,20), columns = ('col %d' % i for i in range(20)) )

sample = pd.DataFrame(np.random.randint(1,20,2) for i in range(10))

my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
display(pd.DataFrame(my_2darray))


sample = pd.DataFrame({'type' : ['k','y','k'],
                       'a' : [1,2,np.nan]},index=[1,2,3])
display(pd.DataFrame(sample))


0  1  2
0  1  2  3
1  4  5  6

type    a
1    k  1.0
2    y  2.0
3    k  NaN

In [16]:
# np.random.randn -> 평균 0 , 표준편차 1인 표준정규분포 난수를 matrix array(n,m)으로 생성 
df = pd.DataFrame(np.random.randn(6,4), index = [i for i in range(6)] , columns = list('ABCD'))
display(df)

A         B         C         D
0  2.065152 -1.360815 -1.308379  0.950800
1 -2.387672  1.867302 -0.136879  1.003140
2  0.471534 -0.635785  1.205115 -0.415499
3  0.437057 -0.214154  1.162567  0.348693
4 -1.828993  1.152551 -0.546035 -0.950850
5  0.029409  0.613722 -0.060319 -0.766462

#### np.where을 통한 조건부 정리

In [ ]:
#np.where 
skimming_data2['group'] = np.where(skimming_data2['skimm'].between(4,6),'4~6',
                                  np.where(skimming_data2['skimm'].between(6,10),'7~10', '10~'))
# inull로 np where 
total_data['edge_crack'] = np.where(total_data['HFI 비고'].isnull(),0,1)

https://codetorial.net/numpy/random.html