## Numpy basic _ tips

In [1]:
import numpy as np
import pandas as pd

#### numpy 무작위 추출 _ choice 

In [2]:
list1=[1,2,3,4,5,6]
prob = [1/6,1/6,1/6,1/6,1/6,1/6] 
np.random.choice(list1,3,p=prob, replace=False)  ## 보통 replace를 건드리지 않지만, default는 True로 복원 추출, False의 경우는 비복원 추출로 한번 시행할때, 뽑힌것은 일단 배제하고 다음 것을 뽑는다.

array([3, 2, 5])

#### numpy 난수로 array 형성 

In [3]:
# 0에서 1사이의 값 중에서 난수 생성. 
# 0~1 사이의 숫자로 10 by 10 array 생성 
np.random.rand(10,10)    

array([[0.75655495, 0.54229995, 0.2938064 , 0.34251635, 0.87346346,
        0.12448895, 0.38295403, 0.62309372, 0.96557001, 0.9552338 ],
       [0.49226343, 0.02306398, 0.6047702 , 0.81711143, 0.50116237,
        0.79567899, 0.3776563 , 0.92947751, 0.32051512, 0.16764266],
       [0.86424992, 0.29109518, 0.93400834, 0.53939549, 0.54134317,
        0.83186477, 0.91360612, 0.05301847, 0.38165256, 0.50949076],
       [0.61248237, 0.52767267, 0.0816472 , 0.22515444, 0.93337001,
        0.38461556, 0.40993307, 0.10251914, 0.03726004, 0.55284268],
       [0.65283898, 0.22797612, 0.32267048, 0.6940634 , 0.0715051 ,
        0.39518244, 0.8308637 , 0.03321518, 0.0538431 , 0.50554519],
       [0.23475672, 0.96093806, 0.86376456, 0.07713218, 0.5177717 ,
        0.53722854, 0.8951199 , 0.72357269, 0.69101556, 0.4260986 ],
       [0.50721065, 0.70465191, 0.75237426, 0.62677786, 0.69412689,
        0.18661746, 0.6796119 , 0.1924238 , 0.73109063, 0.27648748],
       [0.34560875, 0.03269558, 0.4686939

#### numpy _ 정규분포

In [4]:
# 표준 정규분포에서 무작위 숫자 추출  // [0, 1) 범위에서 균일한 분포
np.random.randn(10,2)

array([[-1.48856603,  1.03303172],
       [ 0.40694919, -0.93538376],
       [ 0.38811512,  1.9694033 ],
       [-2.2394653 , -1.10709295],
       [-0.15486786, -1.08636304],
       [-0.03321779, -1.0427401 ],
       [ 0.96278244, -0.69532324],
       [ 0.62783753, -0.30962165],
       [-0.37855707, -1.65981281],
       [-0.13517128, -0.61759786]])

In [5]:
# 표준정규분포 N(1, 0)이 아닌, 평균 μ, 표준편차 σ 를 갖는 정규분포 N(μ, σ2)의 난수를 생성
#σ * np.random.randn(…) + μ 와 같은 형태로 사용할 수 있습니다.
sigma, mu = 1.5, 2.0
c = sigma * np.random.randn(5) + mu
print(c)

[2.3330984  1.40767875 2.2503513  4.06169681 2.17450277]


#### numpy _ random randint, normal

In [6]:
# random.randint() 함수는 [최소값, 최대값)의 범위에서 임의의 정수
np.random.randint(2, size=5) # 는 [0, 2) 범위에서 다섯개의 임의의 정수를 생성.
np.random.randint(2, 4, size=5) # 는 [2, 4) 범위에서 다섯개의 임의의 정수를 생성합.
np.random.randint(1, 5, size=(2, 3)) # 는 [1, 5) 범위에서 (2, 3) 형태의 어레이를 생성합.

# random.normal() 함수는 정규 분포 (Normal distribution)로부터 샘플링된 난수를 반환
a = np.random.normal(0, 1, 2) # 어레이 a는 정규 분포 N(0,1)로부터 얻은 임의의 숫자 2개,
b = np.random.normal(1.5, 1.5, 4) # 어레이 b는 정규 분포 N(1.5,1.52)로부터 얻은 임의의 숫자 4개,
c = np.random.normal(3.0, 2.0, (2, 3)) # 어레이 c는 정규 분포 N(3.0,2.02)로부터 얻은 (2, 3) 형태의 임의의 숫자 어레이.           

In [7]:
print(a)
print(b)
print(c)

[1.42309307 0.21696804]
[ 0.98482157  1.74666719 -0.6996845  -0.36358576]
[[ 3.40270237  4.42859599  1.56577173]
 [ 7.32941811 -0.78265778  0.6730633 ]]


#### numpy random과 array 매서드로 dataframe

In [8]:
pd.DataFrame( np.random.randn(10,20), columns = ('col %d' % i for i in range(20)) )

sample = pd.DataFrame(np.random.randint(1,20,2) for i in range(10))

my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
display(pd.DataFrame(my_2darray))

0  1  2
0  1  2  3
1  4  5  6

#### np.where을 통한 조건부 정리

In [9]:
#np.where 
skimming_data2['group'] = np.where(skimming_data2['skimm'].between(4,6),'4~6',
                                  np.where(skimming_data2['skimm'].between(6,10),'7~10', '10~'))
# inull로 np where 
total_data['edge_crack'] = np.where(total_data['HFI 비고'].isnull(),0,1)

NameError: name 'skimming_data2' is not defined

https://codetorial.net/numpy/random.html