## Numpy basic _ tips

In [4]:
import numpy as np
import pandas as pd

#### numpy 무작위 추출 _ choice 

In [22]:
list1=[1,2,3,4,5,6]
prob = [1/6,1/6,1/6,1/6,1/6,1/6] 
np.random.choice(list1,3,p=prob, replace=False)  ## 보통 replace를 건드리지 않지만, default는 True로 복원 추출, False의 경우는 비복원 추출로 한번 시행할때, 뽑힌것은 일단 배제하고 다음 것을 뽑는다.

array([4, 5, 2])

#### numpy 난수로 array 형성 

In [28]:
# 0에서 1사이의 값 중에서 난수 생성. 
# 0~1 사이의 숫자로 10 by 10 array 생성 
np.random.rand(10,10)    

array([[0.01808011, 0.20809993, 0.09017858, 0.2854382 , 0.71755501,
        0.91994279, 0.95210318, 0.63479044, 0.34765927, 0.66209871],
       [0.92033739, 0.76977819, 0.63033373, 0.2181971 , 0.92615176,
        0.24049826, 0.50949897, 0.09370746, 0.23502789, 0.07065218],
       [0.93955968, 0.13461022, 0.91635439, 0.00268566, 0.25819833,
        0.00742437, 0.08885656, 0.2655885 , 0.95159288, 0.75958328],
       [0.79458619, 0.93271671, 0.47099537, 0.30797527, 0.96533085,
        0.41744476, 0.32143159, 0.61487081, 0.41362856, 0.85851922],
       [0.11211618, 0.42902614, 0.8887866 , 0.45239571, 0.98818244,
        0.21280463, 0.02274959, 0.8803454 , 0.5485907 , 0.77485667],
       [0.65606756, 0.88236001, 0.15561646, 0.88284958, 0.07541149,
        0.39645033, 0.16361383, 0.10797754, 0.07593785, 0.3131805 ],
       [0.1646172 , 0.27237641, 0.64521472, 0.93732194, 0.37439192,
        0.74657684, 0.83884363, 0.41003682, 0.48648778, 0.68986858],
       [0.62392227, 0.77770107, 0.2984240

#### numpy _ 정규분포

In [29]:
# 표준 정규분포에서 무작위 숫자 추출  // [0, 1) 범위에서 균일한 분포
np.random.randn(10,2)

array([[-1.72148351, -1.76819578],
       [ 0.03560533,  0.03633646],
       [-0.60163066, -0.74867023],
       [-0.0023477 ,  1.45199798],
       [ 0.67349473,  0.38725633],
       [ 0.12084439, -1.18787731],
       [ 1.00833583,  0.87480759],
       [ 0.73064373, -0.77875454],
       [ 0.73166039,  0.93959364],
       [-0.2040207 , -0.98344727]])

In [26]:
# 표준정규분포 N(1, 0)이 아닌, 평균 μ, 표준편차 σ 를 갖는 정규분포 N(μ, σ2)의 난수를 생성
#σ * np.random.randn(…) + μ 와 같은 형태로 사용할 수 있습니다.
sigma, mu = 1.5, 2.0
c = sigma * np.random.randn(5) + mu
print(c)

[-0.13836795  1.93087989  3.96097302  3.95770531  2.08882578]


#### numpy _ random randint, normal

In [23]:
# random.randint() 함수는 [최소값, 최대값)의 범위에서 임의의 정수
np.random.randint(2, size=5) # 는 [0, 2) 범위에서 다섯개의 임의의 정수를 생성.
np.random.randint(2, 4, size=5) # 는 [2, 4) 범위에서 다섯개의 임의의 정수를 생성합.
np.random.randint(1, 5, size=(2, 3)) # 는 [1, 5) 범위에서 (2, 3) 형태의 어레이를 생성합.

# random.normal() 함수는 정규 분포 (Normal distribution)로부터 샘플링된 난수를 반환
a = np.random.normal(0, 1, 2) # 어레이 a는 정규 분포 N(0,1)로부터 얻은 임의의 숫자 2개,
b = np.random.normal(1.5, 1.5, 4) # 어레이 b는 정규 분포 N(1.5,1.52)로부터 얻은 임의의 숫자 4개,
c = np.random.normal(3.0, 2.0, (2, 3)) # 어레이 c는 정규 분포 N(3.0,2.02)로부터 얻은 (2, 3) 형태의 임의의 숫자 어레이.           

In [24]:
print(a)
print(b)
print(c)

[0.10083797 2.11860567]
[0.53259917 2.04129711 2.65236731 0.40806498]
[[0.38188509 6.1195246  5.08644936]
 [4.52018516 4.04262745 1.67071739]]


#### numpy random과 array 매서드로 dataframe

In [ ]:
pd.DataFrame( np.random.randn(10,20), columns = ('col %d' % i for i in range(20)) )

sample = pd.DataFrame(np.random.randint(1,20,2) for i in range(10))

my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
display(pd.DataFrame(my_2darray))

#### np.where을 통한 조건부 정리

In [ ]:
#np.where 
skimming_data2['group'] = np.where(skimming_data2['skimm'].between(4,6),'4~6',
                                  np.where(skimming_data2['skimm'].between(6,10),'7~10', '10~'))
# inull로 np where 
total_data['edge_crack'] = np.where(total_data['HFI 비고'].isnull(),0,1)

https://codetorial.net/numpy/random.html